---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: cron-default-tls
  name: cron-default-tls
  namespace: default
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: secret-robot
          automountServiceAccountToken: true
          containers:
          - image: aarato/kubernetes_secret_update
            name: k8stlsupdate
            env:
            - name: SECRETNAME
              value: "mytls"
            - name: TLS_CERT_FILE
              value: "/certificates/cert.pem"
            - name: TLS_KEY_FILE
              value: "/certificates/privkey.pem"
            volumeMounts:
            - mountPath: /certificates
              name: nfs-certificates
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          volumes:
          - name: nfs-certificates
            nfs:
              path: /volume1/nfs-certificates
              server: my.nfs.server
      ttlSecondsAfterFinished: 86400
  schedule: 59 0 * * *
  successfulJobsHistoryLimit: 3
  suspend: false